"""Migraton5

Revision ID: ab90a69c4d8e
Revises: 
Create Date: 2024-02-14 14:17:49.112694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# Assuming you've set your schema name in an environment variable
import os
schema_name = os.getenv('SCHEMA')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('threat_level', sa.Enum('low', 'medium', 'high', name='threatlevel'), nullable=False),
    sa.Column('last_reported', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema=schema_name
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=255), nullable=False),
    sa.Column('character_id', sa.String(length=255), nullable=False, unique=True),
    sa.Column('skill_points', sa.Integer(), nullable=False),
    sa.Column('last_known_location_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=40), nullable=False, unique=True),
    sa.Column('email', sa.String(length=255), nullable=False, unique=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['last_known_location_id'], [f'{schema_name}.systems.id']),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema=schema_name
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players', schema=schema_name)
    op.drop_table('systems', schema=schema_name)
    # ### end Alembic commands ###
